Repository gdsc-ssu/gdgoc-weve-server, pull requests merged in 2025-03, with the labels that each got.

#30 [USER] 전화번호 문자인증 전송 및 검증 기능 구현
  build.gradle
  src/main/java/com/weve/common/config/SmsConfig.java
  src/main/java/com/weve/controller/MessageController.java
  src/main/java/com/weve/controller/UserController.java
  src/main/java/com/weve/domain/User.java
  src/main/java/com/weve/service/MessageService.java
  src/main/java/com/weve/service/UserService.java
Labels: feat

#29 [USER] 마이페이지 정보 조회 및 수정 기능 구현 🚨merge X
  src/main/java/com/weve/controller/UserController.java
  src/main/java/com/weve/service/UserService.java
Labels: feat

#33 [USER] 로그인 및 문자인증 로직 리팩터링
  src/main/java/com/weve/controller/MessageController.java
  src/main/java/com/weve/controller/UserController.java
  src/main/java/com/weve/dto/request/PatchMypageRequest.java
  src/main/java/com/weve/dto/response/MypageResponse.java
  src/main/java/com/weve/service/AuthService.java
  src/main/java/com/weve/service/UserService.java
Labels: feat, refactor

#35 [GCP] 배포 & CI/CD 파이프라인 구축
  .github/workflows/deploy.yml
  Dockerfile
  src/main/java/com/weve/controller/HealthCheckController.java
  src/main/resources/.gitkeep
Labels: feat

#37 [COMMON] Swagger 연동
  build.gradle
  src/main/java/com/weve/WeveApplication.java
  src/main/java/com/weve/common/config/SwaggerConfig.java
  src/main/java/com/weve/controller/AuthController.java
  src/main/java/com/weve/controller/GcsController.java
  src/main/java/com/weve/controller/HealthCheckController.java
  src/main/java/com/weve/controller/MessageController.java
  src/main/java/com/weve/controller/SttController.java
  src/main/java/com/weve/controller/TtsController.java
  src/main/java/com/weve/controller/UserController.java
  src/main/java/com/weve/controller/WorryController.java
  src/main/java/com/weve/dto/request/CreateAnswerRequest.java
  src/main/java/com/weve/dto/request/CreateWorryRequest.java
  src/main/java/com/weve/dto/response/CreateWorryResponse.java
  src/main/java/com/weve/dto/response/GetAnswerResponse.java
  src/main/java/com/weve/dto/response/GetAppreciateResponse.java
  src/main/java/com/weve/dto/response/GetWorriesResponse.java
  src/main/java/com/weve/dto/response/GetWorryResponse.java
  src/main/java/com/weve/dto/response/SpeechToTextResponse.java
  src/main/java/com/weve/dto/response/UploadFileResponse.java
  src/main/java/com/weve/security/SecurityConfig.java
  src/main/java/com/weve/service/WorryService.java
Labels: feat

#38 [SENIOR] 어르신 정보 입력 및 조회 기능 구현
  src/main/java/com/weve/controller/UserController.java
  src/main/java/com/weve/domain/MatchingInfo.java
  src/main/java/com/weve/dto/request/SeniorInfoRequest.java
  src/main/java/com/weve/dto/response/SeniorProfileResponse.java
  src/main/java/com/weve/service/MessageService.java
  src/main/java/com/weve/service/UserService.java
Labels: feat

#40 [API] Swagger 내 Content-Type 표시 문제 해결
  src/main/java/com/weve/controller/GcsController.java
Labels: refactor

#41 [APPRECIATE] 감사편지 작성, 조회, 목록 조회 기능 구현
  src/main/java/com/weve/controller/AppreciateController.java
  src/main/java/com/weve/domain/Appreciate.java
  src/main/java/com/weve/dto/gemini/GeminiResponse.java
  src/main/java/com/weve/dto/request/PostAppreciateRequest.java
  src/main/java/com/weve/dto/response/GetAppreciateListResponse.java
  src/main/java/com/weve/dto/response/GetAppreciateResponse.java
  src/main/java/com/weve/repository/AppreciateRepository.java
  src/main/java/com/weve/service/AppreciateService.java
  src/main/java/com/weve/service/UserService.java
Labels: feat

#43 [OCR] 이미지 텍스트 분석 구현
  .DS_Store
  .gitignore
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/weve/controller/ImageController.java
  src/main/java/com/weve/security/JwtUtil.java
  src/main/java/com/weve/service/ImageService.java
  src/main/resources/.DS_Store
Labels: feat

#45 [APPRECIATE] 감사편지 목록 조회 반환 형식 리팩터링
  src/main/java/com/weve/dto/response/AppreciateDto.java
  src/main/java/com/weve/dto/response/GetAppreciateListResponse.java
  src/main/java/com/weve/service/AppreciateService.java
Labels: refactor

#47 [USER] 문자인증용 도메인 속성 분리 리팩터링
  src/main/java/com/weve/domain/Sms.java
  src/main/java/com/weve/domain/User.java
  src/main/java/com/weve/repository/SmsRepository.java
  src/main/java/com/weve/service/MessageService.java
Labels: refactor
